name: copycat_pro
description: "A new Flutter package project."
version: 2.0.0
homepage: https://github.com/raj457036/copycat_pro
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  copycat_base:
    path: ../copycat_base
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  injectable: ^2.4.2
  get_it: ^7.7.0
  universal_io: ^2.2.2
  purchases_flutter: ^9.2.0
  purchases_ui_flutter: ^9.2.0
  retry: ^3.1.2
  supabase_flutter: ^2.9.1
  supabase_auth_ui: ^0.5.5
  googleapis: ^13.1.0
  dartz: ^0.10.1
  url_launcher: ^6.3.0
  form_validator: ^2.1.1
  freezed_annotation: ^2.4.4
  super_clipboard: ^0.9.1
  super_drag_and_drop: ^0.9.1
  package_info_plus: ^8.0.0
  rxdart: ^0.28.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator:  ^2.6.2
  build_runner: ^2.4.13
  freezed: 2.5.7